apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
spec:
  rules:
  -  http:
      paths:
      - pathType: Prefix
        path: /static
        backend:
          service:
            name: giropops-senhas
            port: 
              number: 5000
