apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
  annotations:
    nginx.ingress.kubernetes.io/rewrite: /
spec:
  rules:
  -  http:
      paths:
      - pathType: Prefix
        path: /giropops-senhas
        backend:
          service:
            name: giropops-senhas
            port: 
              number: 5000
#Site com imagens quebradas
